### ISSUE TITLE
Add a volume adjust to the player please [eob]

### ISSUE THREAD

**Issue by negge** [orhun/CoolModFiles#2]

**Comment by mash-97** [comment]
YO! I like these kind of projects. Though I'm not really proficient in JS and don't know Next.js. But I think I'll go passionate about this. So in order to contribute, can you give me a basic guideline about how can I struggle with this issue?

**Comment by orhun** [comment]
> YO!

Hey!

> I like these kind of projects. Though I'm not really proficient in JS and don't know Next.js. But I think I'll go passionate about this. 

I'm glad to hear someone's interested in this project!

> So in order to contribute, can you give me a basic guideline about how can I struggle with this issue?

Of course.

Basically what we need is adjusting the volume via calling the [libopenmpt](https://lib.openmpt.org/libopenmpt/) functions. We're using a web assembly file for importing these. (See [/bin](https://github.com/orhun/CoolModFiles/tree/master/public/bin)) Last time I checked, I couldn't find any function related to adjusting volume but I cannot say I made a in-depth search. Maybe we should update the version of the library, I don't know. So you can start by diving into `libopenmpt` and see what can we do in order to adjust the volume since all the "playing" related operations are handled by this library. Also you can check what else we can use to achieve that.

Then we can basically update the front-end. e.g. Adding another slider to the `Player` component(s). (See [Player.js](https://github.com/orhun/CoolModFiles/blob/master/components/Player.js) & [Player.module.scss](https://github.com/orhun/CoolModFiles/blob/master/components/Player.module.scss))

**Comment by mash-97** [comment]
Thank you  for your precious response. I did some researches how you guided. Most of the tools above are new to me.  `libopenmpt` is to some extent low-level library to me that I tried to look for the other way. I found `web audio api` 's `AudioContext` promising, as it provides a way to control the volume via it's `GainNode`.

**Comment by orhun** [comment]
> I found `web audio api` 's `AudioContext` promising, as it provides a way to control the volume via it's `GainNode`.

Sounds nice. Any ideas how can we implement that into our current player?

**Comment by Cthulhu2** [comment]
[openmpt_module_set_render_param](https://lib.openmpt.org/doc/group__openmpt__module__render__param.html#ga3bf1d3428ae71694f7c11955410eb489) and `OPENMPT_MODULE_RENDER_MASTERGAIN_MILLIBEL` can be used. Something like that:
```javascript
// chiptune2.js

const OPENMPT_MODULE_RENDER_MASTERGAIN_MILLIBEL = 1
...
function ChiptuneJsConfig(repeatCount, volume) {
   ...
  this.volume = volume;
}

/**
 * Set player volume
 * @param volume Integer, empiric -6000 (silence) .. 2000 (too loud)
 */
ChiptuneJsPlayer.prototype.setVolume = function (volume) {
  this.config.volume = volume
  if (this.currentPlayingNode != null) {
    libopenmpt._openmpt_module_set_render_param(
      this.currentPlayingNode.modulePtr,
      OPENMPT_MODULE_RENDER_MASTERGAIN_MILLIBEL,
      volume,
    );
  }
};

ChiptuneJsPlayer.prototype.createLibopenmptNode = function(buffer, config) {
  ...
  libopenmpt._openmpt_module_set_render_param(
    processNode.modulePtr,
    OPENMPT_MODULE_RENDER_MASTERGAIN_MILLIBEL,
    config.volume,
  );
  ...
}
```

**Comment by Cthulhu2** [comment]
Also, @deskjet in [Volume support #17](https://github.com/deskjet/chiptune2.js/issues/17#issuecomment-191489961) offer the hackish approach with `GainNode`:
```javascript
// create a GainNode
var gain = player.context.createGain()

// wire gain to speaker output
gain.connect(player.context.destination)

// disconnect internal ScriptProcessorNode from speakers
player.currentPlayingNode.disconnect()

// wire script processor to gain
player.currentPlayingNode.connect(gain)

// make it quieter
gain.gain.value = 0.5
```

**Comment by orhun** [comment]
![rec](https://user-images.githubusercontent.com/24392180/145888932-2c74b9c8-7a7b-4a13-ad56-adedee870d79.gif)
