### ISSUE TITLE
Download all favorited mods at once

### ISSUE THREAD

**Issue by WKFO** [orhun/CoolModFiles#26]
Preferably via a button in the expanding "Favorite Mods" section.

**Comment by orhun** [comment]
I think there isn't an easy way of doing this in the browser since "downloading" basically means redirecting to `https://api.modarchive.org/downloads.php?moduleid=<id>`. One possible solution is spawning a million tabs to download each liked mod but that's suboptimal. In this case I'd suggest downloading `coolmods.json` by clicking on the "Favorite Mods" text and then downloading the files by running a command like this:

```sh
cat coolmods.json | jq '.[].id' | xargs -I {} curl -O -J "https://api.modarchive.org/downloads.php?moduleid={}"
```

@bufgix any thoughts?

**Comment by bufgix** [comment]
I think we can download with `fetch` without open new tabs. if we don't get stuck with CORS errors, we can do this.

**Comment by orhun** [comment]
> I think we can download with `fetch` without open new tabs. if we don't get stuck with CORS errors, we can do this.

Cool! I have never heard of [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) before. Can you implement this?

**Comment by bufgix** [comment]
> > I think we can download with `fetch` without open new tabs. if we don't get stuck with CORS errors, we can do this.
> 
> Cool! I have never heard of [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) before. Can you implement this?

Sure
