### ISSUE TITLE
Page refresh message shown on first visit

### ISSUE THREAD

**Issue by WKFO** [orhun/CoolModFiles#56]
In Firefox 110.0, the first time you enter CMF, it shows a page refresh message on the button, not a first time welcome message.

**Comment by orhun** [comment]
This is cumbersome.

https://github.com/orhun/CoolModFiles/blob/2f075f1dfbdd4c121c5d5862204e9fd83078040f/pages/index.js#L42-L54

As you can see, we store the variable `refresh` (bool) in the local storage to check if the page is refreshed or not. So it is set to `true` when the page [gets unloaded](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event). The problem is it always stays as `true` for the next visits of the landing page.

It is set to `false` after a "refresh" message is shown but I assume it is not working.

Any ideas @Cthulhu2?

**Comment by orhun** [comment]
Oh yeah, using `sessionStorage` definitely makes sense. I haven't heard about using the 2nd option.

Do you mind going ahead and creating a PR or should I do it?

**Comment by Cthulhu2** [comment]
>  I haven't heard about using the 2nd option

Me neither. And there are not so many [usages](https://github.com/search?q=performance.getEntriesByType(%22navigation%22)+reload+language%3AJavaScript&type=code&p=1). We'll use `sessionStorage`.
